# Generated by Django 4.1 on 2023-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traning',
            old_name='workout',
            new_name='cWorkout',
        ),
        migrations.AddField(
            model_name='traning',
            name='sWorkout',
            field=models.ManyToManyField(to='exercise.seriesworkout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
