# Generated by Django 4.1 on 2023-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_rename_workout_traning_cworkout_traning_sworkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
