# Generated by Django 4.1 on 2023-06-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exercise_isaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesworkout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='circuitworkout',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='traning',
            name='sWorkout',
        ),
        migrations.DeleteModel(
            name='Reps',
        ),
        migrations.DeleteModel(
            name='SeriesWorkout',
        ),
    ]
