# Generated by Django 4.1 on 2023-06-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_remove_seriesworkout_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.reps')),
            ],
        ),
        migrations.AddField(
            model_name='circuitworkout',
            name='exercises',
            field=models.ManyToManyField(to='exercise.reps'),
        ),
        migrations.AddField(
            model_name='traning',
            name='sWorkout',
            field=models.ManyToManyField(to='exercise.seriesworkout'),
        ),
    ]
